config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Routes to discover page
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :reading_lists, only: [:index, :show] do
    member do
      patch :mark_as_read
    end
    resources :trackers, only: [:new, :create]
  end

  # Nested routes all need the key rather than the id otherwise it will crash if the book not in DB
  resources :books, param: :key, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :reading_lists, only: [:create] do
      collection do
        post :create_read
      end
    end
  end

  get "/genres", to: "books#genres_index"
  patch "/reading_lists/:id", to: "reading_lists#deactivate", as: :deactivate

  resources :trackers, only: [:index, :update] do
    resources :reading_sessions, only: [:new, :create, :edit, :update]
  end
end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_one :tracker, dependent: :destroy

  validates :book, uniqueness: { scope: :user }

  def read?
    read
  end
end

app/controllers/reading_lists_controller.rb
class ReadingListsController < ApplicationController
  before_action :set_reading_list, only: [:show, :deactivate, :mark_as_read]

  def index
    @reading_lists = ReadingList.where(active: true, user_id: current_user)
    @reading_lists_done = ReadingList.where(active: false, user_id: current_user)
    @books_read = current_user.reading_lists.where(read: true).includes(:book).map(&:book)

    # For reviews tab
    @reviews = Review.where(user_id: current_user)
    book_ids = @reviews.map { |review| review.book_id } # Extract all book IDs
    @books_reviewed = Book.where(id: book_ids)
  end

  def show
    @tracker = Tracker.find_by(reading_list_id: @reading_list)
    @reading_session = ReadingSession.find_by(tracker_id: @tracker, active: true)
    @reading_sessions_done = ReadingSession.where(tracker_id: @tracker, active: false)
  end

  def create
    @user = current_user
    @book = Book.find_by(key: params[:book_key])
    @reading_list = ReadingList.new
    @reading_list.user = @user
    @reading_list.book = @book

    if @reading_list.save
      respond_to do |format|
        format.html { redirect_to book_path(@book) }
        format.js   # Trigger JS response for dynamic update
      end
    else
      @reading_list = ReadingList.find_by(user: current_user, book: @book)
      @reading_list.active = true
      @reading_list.save
      respond_to do |format|
        format.html { redirect_to @book }
        format.js   # Trigger JS response for dynamic update
      end
    end
  end

  def create_read
    @user = current_user
    @book = Book.find_by(key: params[:book_key])
    @reading_list = ReadingList.new
    @reading_list.user = @user
    @reading_list.book = @book
    @reading_list.read = true
    @reading_list.active = false

    if @reading_list.save
      respond_to do |format|
        format.html { redirect_to @book}
        format.js   # Trigger JS response for dynamic update
      end
    end
  end

  def deactivate
    @reading_list.active = false
    @reading_list.save
    redirect_to reading_lists_path
  end

  def mark_as_read
    @reading_list.update(read: true)
    redirect_to trackers_path #(@reading_list.book)
  end

  private

  # comment
  def set_reading_list
    @reading_list = ReadingList.find(params[:id])
  end
end

app/views/reading_lists/_current.html.erb
  <%# <%= button_to "Remove from List", deactivate_path(@reading_list), method: :patch, data: { turbo_method: :patch, confirm: "Are you sure?" }  %>
  <div class="card p-2 text-center m-3 mx-0 bf-card">
    <div style="margin-bottom: 12px;">
      <%= image_tag @reading_list.book.cover_url, class: "bf-card-img mt-2" %>
    </div>
    <div>
      <h1 id="bf-text-title"><%= @reading_list.book.title %></h1>
      <p id="bf-text-author">by <%= @reading_list.book.author %></p>
    </div>




    <% if @tracker.blank? %>
      <%= button_to "Start Tracking", reading_list_trackers_path(@reading_list), method: :post, class: "book-detail-add-button" %>
    <% else %>

 <!-- Progress bar -->
      <div class="bf-progress">
        <% total_pages = @reading_list.book.page_count %>
        <% current_page = @tracker.current_page %>
        <% progress_percentage = total_pages.positive? ? (current_page.to_f / total_pages * 100).round : 0 %>

        <div class="bf-progress-bar" style="width: <%= progress_percentage %>%;"></div>
        <div class="bf-progress-text" style="top:0px"><%= progress_percentage %>%</div>
      </div>


<!--
      <div class="bf-text-box">
        <div class="d-flex justify-content-between bf-text-time">
          <p>Time spent: </p>
          <p><strong><%= Time.at(@tracker.total_minutes_spent).utc.strftime("%H:%M:%S") %></strong></p>
        </div>
        <div class="d-flex justify-content-between bf-text-pages">
          <p>Current Page:</p>
          <p><strong><%= @tracker.current_page %></strong></p>
        </div>
      </div>
-->
  </div>


      <div class="bf-sessions text-center" >
        <% if @reading_session.present? && @reading_session.active %>

          <%# <p><small>Session is still ongoing</small></p> %>

          <button type="button" class="bf-btn-sessions" data-bs-toggle="modal" data-bs-target="#SessionEndModal">
            End
          </button>
          <div data-controller="stopwatch">
           <strong><p class="bf-stopwatch-text bf-btn-margin" data-stopwatch-target="timer">00:00</p></strong>
          </div>

          <div class="modal fade" id="SessionEndModal" tabindex="-1" aria-labelledby="SessionEndModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 w-100 text-center" id="SessionEndModalLabel">Session End</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                  <!-- <p>Started at: <%= Time.at(@reading_session.session_start).utc.strftime("%H:%M") %> -->
                  <p>Enter new page number to end the session</p>
                  <%= form_with(model: @reading_session, url: tracker_reading_session_path(tracker_id: @tracker, id: @reading_session), method: :patch) do |form| %>
                    <div class="d-flex flex-column">
                      <%= form.number_field :page_count, value: @tracker.current_page, class: "mb-2 bf-form-text-input" %>
                      <%= form.submit "End Session", class: "book-detail-add-button" %>
                    </div>
                  <% end %>

                </div>

              </div>
            </div>
          </div>


        <% else %>
          <%= button_to "Start Session", tracker_reading_sessions_path(@tracker), method: :post, data: { turbo_method: :post }, class: "bf-btn-sessions"%>
        <% end %>
      </div>


    <% end %>

app/views/reading_lists/_history.html.erb
<h2>Session History</h2>
<%# Done sessions %>
<!--
<ul>
  <% @reading_sessions_done.each do |sess| %>
    <li><%= sess.page_count %></li>
    <li><%= sess.session_start %></li>
    <li><%= sess.session_end %></li>
    <li><%= sess.duration %></li>
  <% end %>
</ul>
-->


<% if @reading_sessions_done.blank? %>
  <p>No sessions done yet</p>
<% else %>
 <%= render "session" %>
<% end %>

app/views/reading_lists/_library_all.html.erb
  <% if @reading_lists.empty? %>
    <p>There are no Books yet.</p>
  <% else %>
    <div class="books">
      <% @reading_lists.each do |reading_list| %>
        <div class="book-card">
          <% if reading_list.book.cover_url.present? %>
            <div class="book-cover-container">
              <%= link_to book_path(reading_list.book) do %>
                <%= image_tag reading_list.book.cover_url, alt: "Book Cover", class: "book-cover" %>
              <% end %>
            </div>
          <% else %>
            <div class="book-cover-container">
              <%= link_to book_path(reading_list.book) do %>
                <%= image_tag 'Discover/missingbook.jpeg', alt: 'No Cover', class: 'book-cover' %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/reading_lists/_library_read.html.erb
<div class="index-container">
  <div class="book-section">
    <div class="books">
      <% if books_read.present? %>
        <% books_read.each do |book| %>
          <div class="book-card">
            <% if book.cover_url.present? %>
              <div class="book-cover-container">
                <%= link_to book_path(book) do %>
                  <%= image_tag book.cover_url, alt: "Book Cover", class: "book-cover" %>
                <% end %>
              </div>
            <% else %>
              <div class="book-cover-container">
                <%= link_to book_path(book) do %>
                  <%= image_tag 'Discover/missingbook.jpeg', alt: 'No Cover', class: 'book-cover' %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p>No books have been marked as read yet.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/reading_lists/_reviewed.html.erb
<% @reviews.each do |review| %>
  <div class="review-card" data-controller="toggle">
    <% book = Book.find(review.book_id) %>
    <div class="image-container">
      <%= image_tag book.cover_url.present? ? book.cover_url : 'Discover/missingbook.jpeg', alt: book.title, class: "review-card-img mt-2" %>
    </div>

    <h4><%= review.title %></h4>
    <p><%= review.content %></p>
    <div>
      <%# <strong>Rating:</strong> %>
      <% (1..5).each do |star| %>
        <% if review.rating >= star %>
          <i class="fa-solid fa-star" style="color: #FFD700;"></i>
        <% else %>
          <i class="fa-regular fa-star" style="color: #FFD700;"></i>
        <% end %>
      <% end %>
    </div>

      <button type="button" data-action="click->toggle#fireEdit" class="edit-review-btn">
        <i class="fa-solid fa-pen" style="margin-right: 8px;"></i>Edit
      </button>
      <div data-toggle-target="toggleEdit" class="d-none">
        <div id="edit-form" class="form">
          <p style="margin-top: 20px; font-weight: bold;">Edit review for <%= book.title %></p>
          <%= simple_form_for([book, review], url: book_review_path(book, review), html: { autocomplete: "off" }) do |f| %>
            <%= f.input :title, label: "Title", autocomplete: "off", input_html: { class: "input-form" } %>
            <%= f.input :content, autocomplete: "off", input_html: { class: "input-form" } %>
            <%= f.input :rating, label: "Rating", input_html: { class: "input-form" } %>
            <%= f.button :submit, value: "Update Review", class: "book-detail-submit-review-btn" %>
          <% end %>
        </div>
      </div>
      <%= link_to book_review_path(book, review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "delete-review-btn" do %>
        <i class="fa-solid fa-x" style="margin-right: 8px;"></i>Delete
      <% end %>

  </div>
<% end %>

app/views/reading_lists/_session.html.erb
<% @reading_sessions_done.sort_by { |ses| -ses.session_start.to_i }.each do |ses| %>
  <div class="session-card bf-session-card">
    <div class="bf-session-info">Duration: <%= (ses.duration / 3600).to_i %> Hrs <%= (ses.duration % 3600 / 60).to_i %> Min <%= (ses.duration % 60).to_i %> Sec</div class="bf-session-info">
    <div class="bf-session-info">Page Milestone<br><%= ses.page_count %></div class="bf-session-info">
    <div class="bf-session-info">Session started: <%= ses.session_start.strftime("%B %d, %Y %I:%M %p") %></div class="bf-session-info">
    <div class="bf-session-info">Session ended: <%= ses.session_end.strftime("%B %d, %Y %I:%M %p") %></div class="bf-session-info">
  </div>
<% end %>

app/views/reading_lists/_stats.html.erb
<% if @tracker.blank? %>
  <p>Not tracked yet</p>
<% else %>

<div class="bf-card p-3">

  <div class="d-flex justify-content-between bf-text-time mb-0">
      <p>Total time spent: </p>
      <p>
        <strong><%= @tracker.total_minutes_spent / 3600 %></strong> H,
        <strong><%= (@tracker.total_minutes_spent % 3600) / 60 %></strong> M,
        <strong><%= @tracker.total_minutes_spent % 60 %></strong> S
      </p>
  </div>

  <div class="d-flex justify-content-between bf-text-pages">
    <p>Current page: </p>
    <p>
    <strong><%= @tracker.current_page %></strong> / <%= @reading_list.book.page_count %>
    </p>
  </div>

</div>

<div class="bf-chart">
  <%= column_chart @reading_sessions_done
                    .group_by_day_of_week(:session_start, format: "%a")
                    .sum(:duration).map { |k, v| [k, v/60] },
                    height: "240px",
                    colors: ["#e49933", "#e36f08"],
                    title: "Reading Sessions Duration",
                    library: {
                      scales: {
                        y: {
                          ticks: {
                            stepSize: 30
                          }
                        }
                      },
                      plugins: {
                        legend: {
                          display: false
                        },
                        tooltip: {
                          enabled: true
                        }
                      },
                      elements: {
                        bar: {
                          borderRadius: 30
                        }
                      }
                    } %>
</div>

<div class="bf-chart">
  <%= column_chart @reading_sessions_done
                      .group_by_day_of_week(:session_start, format: "%a")
                      .average(:page_count).map { |k, v| [k, v.to_i] },
                      height: "240px",
                      colors: ["#e49933", "#e36f08"],
                      title: "Average Pages Read",
                      library: {
                        plugins: {
                          legend: {
                            display: false
                          },
                          tooltip: {
                            enabled: true
                          }
                        },
                        elements: {
                          bar: {
                            borderRadius: 30
                          }
                        }
                      }
                      %>

</div>

<% end %>

app/views/reading_lists/index.html.erb
<div class="outter">
  <div class="scroll-tabs sticky-top">
    <h2 class="index-title">My Books</h2>
    <ul class="nav nav-pills scroll-tabs-nav mb-3 " id="pills-tab" role="tablist">
      <li class="scroll-nav-item" role="presentation">
        <button class="scroll-nav-link active" id="pills-all-tab" data-bs-toggle="pill" data-bs-target="#pills-all" type="button" role="tab" aria-controls="pills-all" aria-selected="true">All</button>
      </li>
      <li class="scroll-nav-item" role="presentation">
        <button class="scroll-nav-link" id="pills-current-tab" data-bs-toggle="pill" data-bs-target="#pills-current" type="button" role="tab" aria-controls="pills-current" aria-selected="false">Current
        </button>
      </li>
      <li class="scroll-nav-item" role="presentation">
        <button class="scroll-nav-link" id="pills-read-tab" data-bs-toggle="pill" data-bs-target="#pills-read" type="button" role="tab" aria-controls="pills-read" aria-selected="false">Read</button>
      </li>
      <li class="scroll-nav-item" role="presentation">
        <button class="scroll-nav-link" id="pills-reviewed-tab" data-bs-toggle="pill" data-bs-target="#pills-reviewed" type="button" role="tab" aria-controls="pills-reviewed" aria-selected="false">Reviews</button>
      </li>
    </ul>
  </div>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab">
      <%= render "library_all" %>
    </div>
    <div class="tab-pane fade" id="pills-current" role="tabpanel" aria-labelledby="pills-current-tab">Current</div>
    <div class="tab-pane fade" id="pills-read" role="tabpanel" aria-labelledby="pills-read-tab">
      <%= render "library_read", books_read: @books_read %>
    </div>
    <div class="tab-pane fade" id="pills-reviewed" role="tabpanel" aria-labelledby="pills-reviewed-tab"><%= render "reviewed" %></div>
  </div>
</div>
    


<!-- <div class="">
  <% @reading_lists_done.each do |done| %>
    <li><%= done.book.title %> <%= link_to "show", reading_list_path(done) %></li>
  <% end %>
</ul> -->

    <%# <ul class="nav nav-pills scroll-tabs-nav">
      <li class="scroll-nav-item">
        <a class="scroll-nav-link active" aria-current="page" href="#">All</a>
      </li>
      <li class="scroll-nav-item">
        <a class="scroll-nav-link" href="#">Current</a>
      </li>
      <li class="scroll-nav-item">
        <a class="scroll-nav-link" href="#">Read</a>
      </li>
      <li class="scroll-nav-item">
        <a class="scroll-nav-link" href="#">Reviewed</a>
      </li>
    </ul> %>

app/views/reading_lists/show.html.erb
<div class="activity-top ">
  <div class="sticky-top">

    <div class="bf-link-back">
      <%= link_to trackers_path do %>
      <i class="fa-solid fa-circle-chevron-left" style="color: rgb(194, 194, 194); font-size: 32px"></i>  <% end %>
    </div>
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-current-tab" data-bs-toggle="pill" data-bs-target="#pills-current" type="button" role="tab" aria-controls="pills-current" aria-selected="true">Active Book</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-stats-tab" data-bs-toggle="pill" data-bs-target="#pills-stats" type="button" role="tab" aria-controls="pills-stats" aria-selected="false">Stats</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-history-tab" data-bs-toggle="pill" data-bs-target="#pills-history" type="button" role="tab" aria-controls="pills-history" aria-selected="false">History</button>
      </li>
    </ul>
  </div>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-current" role="tabpanel" aria-labelledby="pills-current-tab">
      <%= render "current" %>
    </div>
    <div class="tab-pane fade" id="pills-stats" role="tabpanel" aria-labelledby="pills-stats-tab">
      <%= render "stats" %>
    </div>
    <div class="tab-pane fade" id="pills-history" role="tabpanel" aria-labelledby="pills-history-tab">
      <%= render "history" %>
    </div>
  </div>
</div>