config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Routes to discover page
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :reading_lists, only: [:index, :show] do
    member do
      patch :mark_as_read
    end
    resources :trackers, only: [:new, :create]
  end

  # Nested routes all need the key rather than the id otherwise it will crash if the book not in DB
  resources :books, param: :key, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :reading_lists, only: [:create] do
      collection do
        post :create_read
      end
    end
  end

  get "/genres", to: "books#genres_index"
  patch "/reading_lists/:id", to: "reading_lists#deactivate", as: :deactivate

  resources :trackers, only: [:index, :update] do
    resources :reading_sessions, only: [:new, :create, :edit, :update]
  end
end

app/views/shared/_bottom_navbar.html.erb
<nav class="bottom_navbar">
  <ul class="bottom_navbar__tabs">
    <li class="bottom_navbar__tab">
      <% if controller_name == "pages"  %>
        <%= link_to root_path, class: "bottom_navbar__link", id: "discover" do %>
          <i class="fas fa-compass"></i>
          <span>Discover</span>
        <% end %>
      <% else %>
        <%= link_to root_path, class: "bottom_navbar__link", id: "discover" do %>
          <i class="fas fa-compass" style="color:#B6BEC7;"></i>
          <span>Discover</span>
        <% end %>
      <% end %>
    </li>

    <li class="bottom_navbar__tab">
      <% if controller_name == "trackers" || (controller_name == "reading_lists" && action_name == "show") %>
        <%= link_to trackers_path, class: "bottom_navbar__link", id: "reading-activity" do %>
          <i class="fas fa-book-open"></i>
          <span>Reading Activity</span>
        <% end %>
      <% else %>
        <%= link_to trackers_path, class: "bottom_navbar__link", id: "reading-activity" do %>
          <i class="fas fa-book-open" style="color:#B6BEC7;"></i>
          <span>Reading Activity</span>
        <% end %>
      <% end %>
    </li>


    <li class="bottom_navbar__tab">
      <% if controller_name == "reading_lists" && action_name != "show" %>
      <%= link_to reading_lists_path, class: "bottom_navbar__link", id: "my-books" do %>
        <i class="fa-solid fa-bookmark"></i>
        <span>My Books</span>
      <% end %>
      <% else %>
      <%= link_to reading_lists_path, class: "bottom_navbar__link", id: "my-books" do %>
        <i class="fa-solid fa-bookmark" style="color:#B6BEC7;"></i>
        <span>My Books</span>
      <% end %>
      <% end %>
    </li>
  </ul>
  <div class="home-indicator"></div>
</nav>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_search_bar.html.erb
  <div class="search-bar">
    <%= form_with url: books_path(params[:query]), method: :get, local: true, html: { autocomplete: "off" }, class: "search-form" do |f| %>
      <i class="fa-solid fa-magnifying-glass" style="color: #b8b8b8;"></i>
      <%= f.text_field :query, placeholder: "Search for a book", value: params[:query], class: "search-field" %>
      <%= f.submit "Search", class: "hidden-button" %>
    <% end %>
  </div>

app/views/shared/_top_bar.html.erb
<div class="top-bar">
  <div class="left">
    <span class="time" id="time">00:00</span>
  </div>

    <div class="dynamic-island">
    <span></span>
    </div>

  <div class="right">
    <i class="fa-solid fa-signal" style="color: #000000;"></i>
    <i class="fa-solid fa-wifi" style="color: #000000;"></i>
    <i class="fa-solid fa-battery-full" style="color: #000000;"></i>  </div>
</div>
<script src="script.js"></script>