config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Routes to discover page
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :reading_lists, only: [:index, :show] do
    member do
      patch :mark_as_read
    end
    resources :trackers, only: [:new, :create]
  end

  # Nested routes all need the key rather than the id otherwise it will crash if the book not in DB
  resources :books, param: :key, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :reading_lists, only: [:create] do
      collection do
        post :create_read
      end
    end
  end

  get "/genres", to: "books#genres_index"
  patch "/reading_lists/:id", to: "reading_lists#deactivate", as: :deactivate

  resources :trackers, only: [:index, :update] do
    resources :reading_sessions, only: [:new, :create, :edit, :update]
  end
end

app/views/pages/home.html.erb
<%= content_for :title, "Discover" %>

<div class="discover-container">

  <%= render "shared/search_bar" %>

  <div class="main-banner-container">
    <div class="main-banner">
      <div class="main-banner-content">
        <h1>Bookflow</h1>
        <p>Discover and Share Books</p>
        <p><%= link_to "Log in", new_user_session_path, class: "primary-button" unless user_signed_in? %></p>
      </div>
    </div>
  </div>

  <div class="genres">
    <div class="genres-header">
      <h3><%= link_to "Genres", genres_path %></h3>
      <div class="bf-link-right">
        <%= link_to genres_path do %>
          <i class="fa-solid fa-circle-chevron-right" style="color:rgb(194, 194, 194);"></i>
        <% end %>
      </div>
    </div>

    <div class="genre-buttons">
      <div class="genre-container">
        <%= link_to books_path(genre_query: "Fantasy"), class: "genre-button" do %>
          <%= image_tag("Discover/Fantasy Cover.png", alt: "Fantasy", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Fantasy</div>
      </div>

      <div class="genre-container">
        <%= link_to books_path(genre_query: "Novels"), class: "genre-button" do %>
          <%= image_tag("Discover/Novel Cover.png", alt: "Novels", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Novels</div>
      </div>

      <div class="genre-container">
        <%= link_to books_path(genre_query: "Romance"), class: "genre-button" do %>
          <%= image_tag("Discover/Romance Cover.png", alt: "Romance", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Romance</div>
      </div>

      <div class="genre-container">
        <%= link_to books_path(genre_query: "Thriller"), class: "genre-button" do %>
          <%= image_tag("Discover/Thriller Cover.png", alt: "Thriller", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Thriller</div>
      </div>

      <div class="genre-container">
        <%= link_to books_path(genre_query: "Horror"), class: "genre-button" do %>
          <%= image_tag("Discover/Horror Cover.jpg", alt: "Horror", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Horror</div>
      </div>

      <div class="genre-container">
        <%= link_to books_path(genre_query: "Dystopian"), class: "genre-button" do %>
          <%= image_tag("Discover/Dystopian Cover.jpg", alt: "Dystopian", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Dystopian</div>
      </div>

      <div class="genre-container">
        <%= link_to books_path(genre_query: "Scifi"), class: "genre-button" do %>
          <%= image_tag("Discover/Scifi Cover.jpg", alt: "Sci-fi", class: "genre-image") %>
        <% end %>
        <div class="genre-name">Sci-fi</div>
      </div>
    </div>
  </div>

  <div class="genres">
    <h3>Recommendations</h3>
    <div class="genre-buttons">
      <% @recommended_books.each do |book| %>
        <div class="genre-container">
          <% if book.cover_url.present? %>
            <div class="genre-button">
              <%= link_to book_path(book) do %>
                <%= image_tag book.cover_url, alt: book.title, class: "book-cover" %>
              <% end %>
            </div>
          <% else %>
            <div class="genre-button">
              <%= link_to book_path(book) do %>
                <%= image_tag 'Discover/missingbook.jpeg', alt: 'No Cover', class: 'book-cover' %>
              <% end %>
            </div>
          <% end %>
          <p class="book-rating">
            <%= book.overall_rating.present? ? "<i class='fas fa-star' style='color: #FFD700;'></i> #{number_with_precision(book.overall_rating, precision: 1)}".html_safe : "<i class='fas fa-star' style='color: #FFD700;'></i> n/a".html_safe %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="genres">
    <h3>Today's Top Picks</h3>
    <div class="genre-buttons">
      <% @top_picks.each do |book| %>
        <div class="genre-container">
          <% if book.cover_url.present? %>
            <div class="genre-button">
              <%= link_to book_path(book) do %>
                <%= image_tag book.cover_url, alt: book.title, class: "book-cover" %>
              <% end %>
            </div>
          <% else %>
            <div class="genre-button">
              <%= link_to book_path(book) do %>
                <%= image_tag 'Discover/missingbook.jpeg', alt: 'No Cover', class: 'book-cover' %>
              <% end %>
            </div>
          <% end %>
          <p class="book-rating">
            <%= book.overall_rating.present? ? "<i class='fas fa-star' style='color: #FFD700;'></i> #{number_with_precision(book.overall_rating, precision: 1)}".html_safe : "<i class='fas fa-star' style='color: #FFD700;'></i> n/a".html_safe %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>