config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Routes to discover page
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :reading_lists, only: [:index, :show] do
    member do
      patch :mark_as_read
    end
    resources :trackers, only: [:new, :create]
  end

  # Nested routes all need the key rather than the id otherwise it will crash if the book not in DB
  resources :books, param: :key, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :reading_lists, only: [:create] do
      collection do
        post :create_read
      end
    end
  end

  get "/genres", to: "books#genres_index"
  patch "/reading_lists/:id", to: "reading_lists#deactivate", as: :deactivate

  resources :trackers, only: [:index, :update] do
    resources :reading_sessions, only: [:new, :create, :edit, :update]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :reading_lists, dependent: :destroy

  def to_param
    key
  end

  def strip_tags
    ActionController::Base.helpers.strip_tags(self.summary)
  end

  include PgSearch::Model
  pg_search_scope :search_by_title,
    against: [ :title ],
    using: {
      tsearch: { prefix: true }
    }

    pg_search_scope :search_by_genre,
    against: [ :genre ],
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/books_controller.rb
require "json"
require "open-uri"

class BooksController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  def index
    # Returns books in DB if no search queries present
    @books = Book.all

    # If search queries are present, call API
    if params[:query].present?
      @books = title_search(params[:query])
    elsif params[:genre_query].present?
      session[:genre] = params[:genre_query]
      @books = genre_search(params[:genre_query])
    end
  end

  def show
    @review = Review.new
    # Return instance of book if already in DB, else create a new instance for that book
    if @book = Book.find_by(key: params[:key])
      @book.summary = strip_tags(@book.summary)
      @book
    else
      @book = show_page_search(params[:key], session[:genre])
    end
    @reviews = @book.reviews
    @reading_list = current_user.reading_lists.find_by(book_id: @book.id)
  end

  def genres_index
    @genres = genre_dispatch

  end

  def genre_dispatch
    Rails.cache.fetch("#{current_user.cache_key_with_version}/content") do
    genres = { Fantasy: [], Novels: [], Romance: [], Thriller: [], Mystery: [], Crime: [] }
    genres.each do |key, value|
      value.concat(genre_search(key.to_s))
    end
    genres
  end
  end

  private

  # Pls don't touch this or i will cry
  # TODO: still don't have a rating when you create a new book
  def show_page_search(key, genre)
    url = "https://www.googleapis.com/books/v1/volumes/#{key}?key=#{ENV['GOOGLE_API_KEY']}"
    response = URI.parse(url).read
    data = JSON.parse(response)
    Book.create!(
      title: data["volumeInfo"]["title"],
      author: data["volumeInfo"]["authors"][0],
      year_published: data["volumeInfo"]["publishedDate"],
      summary: strip_tags(data["volumeInfo"]["description"]),
      page_count: data["volumeInfo"]["pageCount"],
      cover_url: data["volumeInfo"]["imageLinks"]&.dig("smallThumbnail"),
      key: key,
      genre: genre
    )
  end

  def title_search(query)
    url = "https://www.googleapis.com/books/v1/volumes?q=#{(query)}
            &startIndex=0&maxResults=40&key=#{ENV["GOOGLE_API_KEY"]}"
    books = base_search(query, url)
  end

  def genre_search(query)
    url = "https://www.googleapis.com/books/v1/volumes?q=subject:#{query}
            &startIndex=0&maxResults=40&key=#{ENV["GOOGLE_API_KEY"]}"
    books = base_search(query, url)
  end

  def base_search(query, url)
      books = []
      response = URI.parse(url).read
      data = JSON.parse(response)
      data["items"].each do |d|
        book = Book.new
        cover_url =  d["volumeInfo"]["imageLinks"]&.dig("smallThumbnail")
        book[:cover_url] = cover_url
        book.key = d["id"]
        books << book
      end
      books
  end
end

app/views/books/genres_index.html.erb
<%= render "shared/search_bar" %>

<% @genres.each do |key, value| %>
  <div class="genres">
    <h3><%= key %></h3>
    <div class="genre-buttons">

        <% value.each do |book| %>
      <div class="genre-container">

          <% if book.cover_url.present? %>
            <div class="genre-button">
              <%= link_to book_path(book) do %>
                <%= image_tag book.cover_url, alt: book.title, class: "book-cover" %>
              <% end %>
            </div>

          <% else %>

            <div class="genre-button">
              <%= link_to book_path(book) do %>
                <%= image_tag 'Discover/missingbook.jpeg', alt: 'No Cover', class: 'book-cover' %>
              <% end %>
            </div>

          <% end %>

        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<%= content_for :title, "Books" %>

<div class="index-container">

  <%= render "shared/search_bar" %>

  <% if params[:query].present? || params[:genre_query].present? %>
    <div class="book-section">
      <h3>Search Results</h3>
      <div class="books">
        <% @books.each do |book| %>
          <div class="book-card">
            <% if book.cover_url.present? %>
              <div class="book-cover-container">
                <%= link_to book_path(book.key) do %>
                  <%= image_tag book.cover_url, alt: "Book Cover", class: "book-cover" %>
                <% end %>
              </div>
            <% else %>
              <div class="book-cover-container">
                <%= link_to book_path(book.key) do %>
                  <%= image_tag 'Discover/missingbook.jpeg', alt: 'No Cover', class: 'book-cover' %>
                <% end %>
              </div>
            <% end %>
           
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <p>No search results found. Try searching for a different book or genre.</p>
  <% end %>

</div>

app/views/books/show.html.erb
<div class="book-detail-container">
  <div class="book-detail-header">
    <div class="book-detail-cover-container">
      <%= image_tag @book.cover_url.present? ? @book.cover_url : 'Discover/missingbook.jpeg', alt: @book.title, class: "book-detail-cover" %>
    </div>
    <div class="book-detail-info">
      <h1><%= @book.title %></h1>
      <p>by <%= @book.author %></p>
      <br>
      <p><strong>Published Year:</strong> <%= @book.year_published %></p>
      <% unless @book.genre.nil? %>
        <p><strong>Genre:</strong> <%= @book.genre %></p>
      <% end %>
      <p><strong>Page Count:</strong> <%= @book.page_count %> pages</p>
      <p>
        <strong>Overall Rating:</strong>
        <i class="fas fa-star" style="color: #FFD700;"></i>
        <%= @book.overall_rating == @book.overall_rating ? @book.overall_rating : number_with_precision(@book.overall_rating, precision: 1) %>
        / 5
      </p>
    </div>
  </div>

  <% if current_user.reading_lists.where(book_id: @book.id, active: true).exists? %>
    <div class="d-flex justify-content-between">
      <%= button_to deactivate_path(@reading_list), method: :patch, data: { turbo_method: :patch, confirm: "Are you sure?" }, class: "book-detail-leave-review-btn" do %>
        <i class="fa-solid fa-x"></i> Remove Book
      <% end %>
      <%= link_to reading_list_path(@reading_list), class: "book-detail-add-button text-decoration-none" do %>
        <i class="fa-solid fa-play me-2"></i> Go to Tracker
      <% end %>
    </div>
  <% else %>
    <div class="d-flex justify-content-center">
      <%= button_to book_reading_lists_path(@book), method: :post, class: "book-detail-add-button", id: "add-to-reading-list-btn", data: { turbo_method: :post } do %>
        <i class="fa-solid fa-plus me-2"></i> Add to Reading List
      <% end %>
    </div>
  <% end %>

  <!-- Mark book as read
  <% if @reading_list %>
    <% if @reading_list.read? %>
      <div class="badge bg-success">Read</div>
    <% else %>
      <%= button_to "Mark as Read", mark_as_read_reading_list_path(@reading_list), method: :patch, class: "btn btn-primary" %>
    <% end %>
  <% else %>
    <%= button_to "Mark as read", create_read_book_reading_lists_path(@book), method: :post, class: "book-detail-add-button", data: { turbo_method: :post } %>
  <% end %>
  -->


  <% if @book.summary.present? %>
    <h4 style="margin-top: 30px;">Summary</h4>
    <p>
      <span class="summary-text"><%= @book.summary.truncate(300) %></span>
      <span id="points">...</span>
      <span id="moreText" style="display: none;"><%= @book.summary %></span>
    </p>
    <a href="#" onclick="toggleText()" id="textButton" style="text-decoration: none; color: black; cursor: pointer;">
      Show More <i class="fa-solid fa-chevron-down"></i>
    </a>
  <% else %>
    <h4 style="margin-top: 30px;">Summary</h4>
    <p>No summary available for this book.</p>
  <% end %>

  <h4 style="margin-top: 30px;">Reviews</h4>
  <!-- Review Form Toggle -->
  <div data-controller="toggle">
    <button type="button" data-action="click->toggle#fireReview" class="book-detail-leave-review-btn">
      <i class="fa-regular fa-comment"></i> Leave a Review
    </button>
    <div data-toggle-target="togglableElement" class="d-none">
      <div id="review-form" class="form">
        <p style="margin-top: 20px; font-weight: bold;">Write a Review for <%= @book.title %></p>
        <%= simple_form_for([@book, @review], html: { autocomplete: "off" }) do |f| %>
          <%= f.input :title, label: "Title", autocomplete: "off", input_html: { class: "input-form" } %>
          <%= f.input :content, autocomplete: "off", input_html: { class: "input-form" } %>
          <%= f.input :rating, label: "Rating", input_html: { class: "input-form" } %>
          <%= f.button :submit, value: "Submit Review", class: "book-detail-submit-review-btn" %>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Reviews Display -->
  <% @reviews.each do |review| %>
    <div class="review" data-controller="toggle">
      <h5><%= review.title %></h5>
      <% user = review.user %>
      <% if user %>
        <p>by <%= user.first_name %> <%= user.last_name %></p>
      <% end %>
      <p><%= review.content %></p>
      <div>
        <%# <strong>Rating:</strong> %>
        <% (1..5).each do |star| %>
          <% if review.rating >= star %>
            <i class="fa-solid fa-star" style="color: #FFD700;"></i>
          <% else %>
            <i class="fa-regular fa-star" style="color: #FFD700;"></i>
          <% end %>
        <% end %>
      </div>

      <!-- Edit & Delete Options for the User's Own Review -->
      <% if review.user == current_user %>
        <button type="button" data-action="click->toggle#fireEdit" class="edit-review-btn">
          <i class="fa-solid fa-pen" style="margin-right: 8px;"></i>Edit
        </button>
        <div data-toggle-target="toggleEdit" class="d-none">
          <div id="edit-form" class="form">
            <p style="margin-top: 20px; font-weight: bold;">Edit review for <%= @book.title %></p>
            <%= simple_form_for([@book, review], url: book_review_path(@book, review), html: { autocomplete: "off" }) do |f| %>
              <%= f.input :title, label: "Title", autocomplete: "off", input_html: { class: "input-form" } %>
              <%= f.input :content, autocomplete: "off", input_html: { class: "input-form" } %>
              <%= f.input :rating, label: "Rating", input_html: { class: "input-form" } %>
              <%= f.button :submit, value: "Update Review", class: "book-detail-submit-review-btn" %>
            <% end %>
          </div>
        </div>
        <%= link_to book_review_path(@book, review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "delete-review-btn" do %>
          <i class="fa-solid fa-x" style="margin-right: 8px;"></i>Delete
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  function toggleText() {
    // Get the elements
    const points = document.getElementById("points");
    const moreText = document.getElementById("moreText");
    const buttonText = document.getElementById("textButton");

    // Toggle visibility
    if (points.style.display === "none") {
      moreText.style.display = "none";
      points.style.display = "inline";
      buttonText.innerHTML = 'Show More <i class="fa-solid fa-chevron-down"></i>';
    } else {
      moreText.style.display = "inline";
      points.style.display = "none";
      buttonText.innerHTML = 'Show Less <i class="fa-solid fa-chevron-up"></i>';
    }
  }
</script>